---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: securitywiki
  namespace: securitywiki-stage
  labels:
    app: securitywiki
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(stg-[a-f0-9]{7})$
spec:
  releaseName: securitywiki
  chart:
    repository: https://mozilla-it.github.io/helm-charts/
    name: securitywiki
    version: "1.0.0"
  values:
    configMap:
      data:
        ENVIRONMENT: stage
        MEMCACHED_PORT: "11211"
        MYSQL_DATABASE: securitywiki
        MYSQL_USER: securitywiki
        SITE_URL: https://securitywiki.allizom.org
    deployment:
      replicaCount: "1"
    externalSecrets:
      enabled: true
      name: securitywiki
      secrets:
      - key: /stage/securitywiki/envvar
        name: MEMCACHED_HOST
        property: MEMCACHED_HOST
      - key: /stage/securitywiki/envvar
        name: MYSQL_HOST
        property: MYSQL_HOST
      - key: /stage/securitywiki/envvar
        name: MYSQL_PASSWORD
        property: MYSQL_PASSWORD
      - key: /stage/securitywiki/envvar
        name: OIDC_CLIENT_ID
        property: OIDC_CLIENT_ID
      - key: /stage/securitywiki/envvar
        name: OIDC_CLIENT_SECRET
        property: OIDC_CLIENT_SECRET
      - key: /stage/securitywiki/envvar
        name: OIDC_CRYPTO_PASSPHRASE
        property: OIDC_CRYPTO_PASSPHRASE
    hpa:
      enabled: false
    image:
      pullPolicy: Always
      repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/securitywiki
      tag: stg-78cc2a3
    ingress:
      hosts:
      - host: securitywiki.stage.mozit.cloud
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: securitywiki
          servicePort: 80
      - host: securitywiki.allizom.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: securitywiki
          servicePort: 80
      le:
        name: prod
      name: securitywiki
      tls:
      - hosts:
        - securitywiki.allizom.org
        secretName: cert-securitywiki-allizom-org
      - hosts:
        - securitywiki.stage.mozit.cloud
        secretName: cert-securitywiki-stage-mozit-cloud
    volume:
      accessModes: ReadWriteMany
      capacityStorage: 100Gi
      create: true
      name: securitywiki-stage
      nfsServer: "fs-d763987d.efs.us-west-2.amazonaws.com"
      storageClassName: efs
      storageRequest: 20Gi
