---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: discourse-stage
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^stage-.*$
  imageRepositoryRef:
    name: discourse
  policy:
    numerical:
      order: asc
