repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
      - id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
  - repo: git://github.com/Yelp/detect-secrets
    rev: v0.14.3
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.40.0
    hooks:
      - id: terraform_fmt
        exclude: \.terraform\/.*$
