---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: moderator
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^(stg-[a-f0-9]{7}-(?P<ts>[0-9]+))$
  imageRepositoryRef:
    name: moderator
  policy:
    alphabetical:
      order: asc

