---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: telegraf-stage
  labels:
    app: telegraf
spec:
  releaseName: telegraf
  chart:
    repository: https://helm.influxdata.com/
    name: telegraf
    version: "1.8.4"
  values:
    envFromSecret: telegraf-influx
    image:
      repo: public.ecr.aws/influxdb/telegraf
      image: 1.16.2-alpine
    service:
      enabled: false
    config:
      agent:
        interval: "300s"
      global_tags:
        cluster: itse-apps-stage-1-infra
      inputs:
        - x509_cert:
            # TODO: define a url that we can take down/break to do
            # functional testing of this setup
            sources:
              - 'https://www.firefox.com:443'
              - 'https://www.mozilla.com:443'
      outputs:
        - influxdb:
            skip_database_creation: true
            urls: ["${INFLUX_URL}"]
            database: "${INFLUX_DB}"
            timeout: "15s"
            username: "${INFLUX_USER}"
            password: "${INFLUX_PW}"
