---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: telegraf

  name: telegraf
  namespace: telegraf-stage

spec:
  chart:
    spec:
      chart: telegraf
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
      version: 1.8.4

  interval: 1m0s
  releaseName: telegraf
  values:
    config:
      agent:
        interval: 300s

      global_tags:
        cluster: itse-apps-stage-1-infra

      inputs:
        - x509_cert:
            sources:
              - https://www.firefox.com:443
              - https://www.mozilla.com:443

      outputs:
        - influxdb:
            database: ${INFLUX_DB}
            password: ${INFLUX_PW}
            skip_database_creation: true
            timeout: 15s
            urls:
              - ${INFLUX_URL}

            username: ${INFLUX_USER}

    envFromSecret: telegraf-influx
    image:
      repo: public.ecr.aws/influxdb/telegraf
      tag: 1.16.2-alpine

    service:
      enabled: false
