---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: pastebin
  name: ingress-nginx
  namespace: pastebin-stage
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.2.0
  interval: 1m0s
  releaseName: pastebin-ingress-nginx
  values:
    controller:
      admissionWebhooks:
        enable: false
      autoscaling:
        enabled: true
        maxReplicas: 4
        minReplicas: 1
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      config:
        proxy-real-ip-cidr: 0.0.0.0/0
        use-forwarded-headers: "true"
        use-proxy-protocol: "false"
      enableCustomResources: false
      ingressClassResource:
        controllerValue: k8s.io/ingress-nginx-pastebin-stage
        default: false
        enabled: true
        name: ingress-nginx-pastebin-stage
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/port: "10254"
            prometheus.io/scrape: "true"
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      scope:
        enabled: true
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: paste.stage.mozit.cloud
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment=stage
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-type: nlb
        externalTrafficPolicy: Local
    rbac:
      create: true
      scope: true
