---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: moderator-image
  namespace: flux-system
spec:
  image: 783633885093.dkr.ecr.us-west-2.amazonaws.com/moderator
  interval: 5m0s

