{
 "title": "Refractr Usage",
 "description": "A quick dashboard to show how refractr is being used",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(nginx_ingress_controller_request_size_count, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per path, filtered by host",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_request_size_count{host=\"$host\"}) by (host, path)\n",
     "legendFormat": "{{host}}, {{path}}"
    }
   ]
  },
  {
   "title": "Requests by host ignoring path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_request_size_count) by (host) - sum(nginx_ingress_controller_request_size_count offset $__range) by (host)\n",
     "legendFormat": "{{host}}, {{path}}"
    }
   ]
  },
  {
   "title": "Requests by host per path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_request_size_count) by (host,path) - sum(nginx_ingress_controller_request_size_count offset $__range) by (host,path)\n",
     "legendFormat": "{{host}}, {{path}}"
    }
   ]
  },
  {
   "title": "Top 3 hosts + paths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum by (host, path) (nginx_ingress_controller_request_size_count)) - sum by (host,path) (nginx_ingress_controller_request_size_count offset $__range)",
     "legendFormat": "{{host}}, {{path}}"
    }
   ]
  },
  {
   "title": "Bottom 5 hosts + paths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(5, sum by (host, path) (nginx_ingress_controller_request_size_count)) - sum by (host,path) (nginx_ingress_controller_request_size_count offset $__range)",
     "legendFormat": "{{host}}, {{path}}"
    }
   ]
  }
 ]
}