---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: etherpad-stage
  labels:
    app: etherpad
spec:
  releaseName: etherpad-ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "3.33.0"
  values:
    controller:
      useIngressClassOnly: true
      enableCustomResources: false
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 4
        targetCPUUtilizationPercentage: 80
        targetMemoryUtilizationPercentage: 80
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      admissionWebhooks:
        enable: false
      scope:
        enabled: true
      config:
        compute-full-forwarded-for: "true"
        enable-real-ip: "true"
        use-forwarded-headers: "true"
        use-proxy-protocol: "false"
        # restrict this to the IP addresses of ELB
        proxy-real-ip-cidr: "172.16.0.0/16"
      service:
        externalTrafficPolicy: "Local"
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=stage"
          external-dns.alpha.kubernetes.io/hostname: "etherpad.stage.mozit.cloud,etherpad.allizom.org"
      metrics:
        enabled: true
        service:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
    rbac:
      create: true
      scope: true
