---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: etherpad
  namespace: etherpad-stage
  labels:
    app: etherpad
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(stg-[a-f0-9]{7})$
spec:
  releaseName: etherpad
  chart:
    repository: https://mozilla-it.github.io/helm-charts/
    name: etherpad
    version: "2.0.0"
  values:
    configMap:
      data: {}
    externalSecrets:
      enabled: true
      secrets:
      - remoteRef:
          key: /stage/etherpad/envvar
          property: ADMIN_PASSWORD
        secretKey: ADMIN_PASSWORD
      - remoteRef:
          key: /stage/etherpad/envvar
          property: DB_HOST
        secretKey: DB_HOST
      - remoteRef:
          key: /stage/etherpad/envvar
          property: DB_NAME
        secretKey: DB_NAME
      - remoteRef:
          key: /stage/etherpad/envvar
          property: DB_PASS
        secretKey: DB_PASS
      - remoteRef:
          key: /stage/etherpad/envvar
          property: DB_USER
        secretKey: DB_USER
      - remoteRef:
          key: /stage/etherpad/envvar
          property: ETHERPAD_API_KEY
        secretKey: ETHERPAD_API_KEY
      - remoteRef:
          key: /stage/etherpad/envvar
          property: ETHERPAD_SESSION_KEY
        secretKey: ETHERPAD_SESSION_KEY
    image:
      pullPolicy: Always
      repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/etherpad
      tag: stg-724a722
    ingress:
      className: ingress-nginx-etherpad-stage
      hosts:
      - host: pad.allizom.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: oidc-gateway
          servicePort: 80
      - host: pad.stage.mozit.cloud
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: oidc-gateway
          servicePort: 80
      le:
        issuer_create: true
        name: prod
      tls:
      - hosts:
        - pad.allizom.org
        secretName: chart-pad-allizom-org
      - hosts:
        - pad.stage.mozit.cloud
        secretName: chart-pad-stage-mozit-cloud
