---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: refractr
  namespace: flux-system

spec:
  filterTags:
    extract: $tag
    pattern: ^(?P<tag>v[0-9]+.[0-9]+.[0-9]+-[0-9]+-g[a-f0-9]{7})$

  imageRepositoryRef:
    name: refractr

  policy:
    semver:
      range: ">=0.0.0-0"
