---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app: pastebin
  name: pastebin
  namespace: pastebin-stage
spec:
  chart:
    spec:
      chart: pastebin
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mozilla-helm-charts
        namespace: flux-system
      version: 0.2.2
  interval: 1m0s
  releaseName: pastebin
  values:
    configMap:
      data:
        DB_PORT: "3306"
        DPASTE_BASE_DOMAIN: paste.allizom.org
        VAL: "5"
    deployment:
      port: "8000"
      replicaCount: "1"
    externalSecrets:
      enabled: true
      name: pastebin
      secrets:
      - remoteRef:
          key: /stage/pastebin/envvar
          property: database_host
        secretKey: DB_HOST
      - remoteRef:
          key: /stage/pastebin/envvar
          property: database_name
        secretKey: DB_NAME
      - remoteRef:
          key: /stage/pastebin/envvar
          property: database_password
        secretKey: DB_PASS
      - remoteRef:
          key: /stage/pastebin/envvar
          property: database_user
        secretKey: DB_USER
      - remoteRef:
          key: /stage/pastebin/envvar
          property: session_key
        secretKey: SESSION_KEY
    image:
      pullPolicy: Always
      repository: 783633885093.dkr.ecr.us-west-2.amazonaws.com/pastebin
      tag: stg-bfb5015
    ingress:
      className: ingress-nginx-pastebin-stage
      hosts:
      - host: paste.stage.mozit.cloud
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      - host: paste.allizom.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      - host: pastebin.allizom.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      - host: pastebin-dev.allizom.org
        paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: pastebin
          servicePort: 80
      le:
        name: prod
      name: pastebin
      tls:
      - hosts:
        - paste.allizom.org
        secretName: cert-paste-allizom-org
      - hosts:
        - pastebin.allizom.org
        secretName: cert-pastebin-allizom-org
      - hosts:
        - pastebin-dev.allizom.org
        secretName: cert-pastebin-dev-allizom-org
      - hosts:
        - paste.stage.mozit.cloud
        secretName: cert-paste-stage-mozit-cloud
