---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pastebin
  namespace: pastebin-stage
  labels:
    app: pastebin
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:^(stg-[a-f0-9]{7})$
spec:
  releaseName: pastebin
  chart:
    repository: https://mozilla-it.github.io/helm-charts/
    name: pastebin
    version: "0.1.1"
  values:
    configMap:
      data:
        DB_PORT: "3306"
        VAL: "5"
    deployment:
      port: "8000"
      replicaCount: "1"
    externalSecrets:
      enabled: true
      name: pastebin
      secrets:
      - key: /stage/pastebin/envvar
        name: DB_HOST
        property: database_host
      - key: /stage/pastebin/envvar
        name: DB_NAME
        property: database_name
      - key: /stage/pastebin/envvar
        name: DB_PASS
        property: database_password
      - key: /stage/pastebin/envvar
        name: DB_USER
        property: database_user
      - key: /stage/pastebin/envvar
        name: SESSION_KEY
        property: session_key
    image:
      pullPolicy: Always
      tag: stg-16c5b9c
    ingress:
      hosts:
        - host: paste.stage.mozit.cloud
          paths:
            - path: /
              pathType: ImplementationSpecific
              serviceName: pastebin
              servicePort: 80
        - host: paste.allizom.org
          paths:
            - path: /
              pathType: ImplementationSpecific
              serviceName: pastebin
              servicePort: 80
        - host: pastebin.allizom.org
          paths:
            - path: /
              pathType: ImplementationSpecific
              serviceName: pastebin
              servicePort: 80
        - host: pastebin-dev.allizom.org
          paths:
            - path: /
              pathType: ImplementationSpecific
              serviceName: pastebin
              servicePort: 80
      le:
        name: prod
      name: pastebin
      tls:
        - hosts:
            - paste.allizom.org
          secretName: cert-paste-allizom-org
        - hosts:
            - pastebin.allizom.org
          secretName: cert-pastebin-allizom-org
        - hosts:
            - pastebin-dev.allizom.org
          secretName: cert-pastebin-dev-allizom-org
        - hosts:
            - paste.stage.mozit.cloud
          secretName: cert-paste-stage-mozit-cloud
