---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: itsre-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./k8s
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system

